apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-deployment
  labels:
    app: watch
spec:
  replicas: 100
  selector:
    matchLabels:
      app: watch
  template:
    metadata:
      labels:
        app: watch
    spec:
      containers:
        - name: watch
          # image 地址得修改
          image: xxxxxx-xxxx-watch:latest
          imagePullPolicy: IfNotPresent
          command: ['sh','-c','sh /home/start.sh']
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1000Mi"
              cpu: "1000m"
